export const girls = [
	{
		name: "Julia",
		source: require("../../assets/mulher1.jpeg"),
		age: 24,
		distance: "1",
		college: "Universidade Católica de Petrópolis",
		city: "Petrópolis",
		online: true,
	},
	{
		name: "Nathalia",
		source: require("../../assets/mulher2.jpg"),
		age: 23,
		distance: "12",
		college: "Estácio",
		city: "Petrópolis",
		online: false,
	},
	{
		name: "Thais",
		source: require("../../assets/mulher3.jpg"),
		age: 28,
		distance: "18",
		online: false,
	},
	{
		name: "Thayna",
		source: require("../../assets/mulher4.jpg"),
		age: 27,
		distance: "16",
		city: "Teresópolis",
		online: true,
	},
	{
		name: "Larissa",
		source: require("../../assets/mulher5.jpg"),
		age: 21,
		distance: "51",
		college: "UFRJ",
		city: "Rio de Janeiro",
		online: true,
	},
];
